[
    {
        "nome_completo": "Maria Oliveira",
        "data_nascimento": "1985-09-12",
        "cpf": "98765432100",
        "telefone": "11987654321",
        "endereco": "Rua das Palmeiras",
        "rua": "Rua B",
        "numero": "456",
        "complemento": "Casa",
        "bairro": "Jardim das Flores",
        "cidade": "Rio de Janeiro",
        "situacao_familia": "Pai e mãe vivos, um irmão",
        "saude_especiais": "Nenhum",
        "observacao_geral": "Cliente muito simpático"
    },
    {
        "nome_completo": "José Santos",
        "data_nascimento": "1978-03-25",
        "cpf": "12312312300",
        "telefone": "11912345678",
        "endereco": "Avenida Central",
        "rua": "Rua C",
        "numero": "789",
        "complemento": "Apartamento 302",
        "bairro": "Centro",
        "cidade": "São Paulo",
        "situacao_familia": "Pai falecido, mãe e irmãos vivos",
        "saude_especiais": "Hipertensão",
        "observacao_geral": "Cliente bastante reservado"
    },
    {
        "nome_completo": "Ana Silva",
        "data_nascimento": "1993-11-08",
        "cpf": "45678912300",
        "telefone": "11955556666",
        "endereco": "Rua dos Coqueiros",
        "rua": "Rua D",
        "numero": "101",
        "complemento": "Casa",
        "bairro": "Praia",
        "cidade": "Fortaleza",
        "situacao_familia": "Pais vivos, sem irmãos",
        "saude_especiais": "Diabetes",
        "observacao_geral": "Cliente muito ativa na comunidade local"
    },
    {
        "nome_completo": "Carlos Souza",
        "data_nascimento": "1980-07-15",
        "cpf": "33322211100",
        "telefone": "11999998888",
        "endereco": "Alameda das Águias",
        "rua": "Rua E",
        "numero": "222",
        "complemento": "Casa",
        "bairro": "Parque das Aves",
        "cidade": "Brasília",
        "situacao_familia": "Pais vivos, um irmão",
        "saude_especiais": "Asma",
        "observacao_geral": "Cliente bastante comunicativo"
    },
    {
        "nome_completo": "Lúcia Ferreira",
        "data_nascimento": "1975-01-30",
        "cpf": "66677788800",
        "telefone": "11944445555",
        "endereco": "Travessa dos Pinheiros",
        "rua": "Rua F",
        "numero": "333",
        "complemento": "Apartamento 201",
        "bairro": "Pinheiros",
        "cidade": "São Paulo",
        "situacao_familia": "Pais falecidos, dois irmãos",
        "saude_especiais": "Artrite",
        "observacao_geral": "Cliente muito educada"
    },
    {
        "nome_completo": "Ricardo Lima",
        "data_nascimento": "1998-12-05",
        "cpf": "11122233300",
        "telefone": "11933334444",
        "endereco": "Avenida das Mangueiras",
        "rua": "Rua G",
        "numero": "444",
        "complemento": "Casa",
        "bairro": "Mangueiral",
        "cidade": "Recife",
        "situacao_familia": "Pais vivos, sem irmãos",
        "saude_especiais": "Nenhum",
        "observacao_geral": "Cliente muito descontraído"
    },
    {
        "nome_completo": "Fernanda Almeida",
        "data_nascimento": "1987-04-18",
        "cpf": "99988877700",
        "telefone": "11977776666",
        "endereco": "Rua dos Girassóis",
        "rua": "Rua H",
        "numero": "555",
        "complemento": "Casa",
        "bairro": "Jardim Primavera",
        "cidade": "Belo Horizonte",
        "situacao_familia": "Pais vivos, dois irmãos",
        "saude_especiais": "Alergia a frutos do mar",
        "observacao_geral": "Cliente bastante extrovertida"
    },
    {
        "nome_completo": "Paulo Gomes",
        "data_nascimento": "1983-06-22",
        "cpf": "77766655500",
        "telefone": "11922223333",
        "endereco": "Avenida dos Lírios",
        "rua": "Rua I",
        "numero": "666",
        "complemento": "Casa",
        "bairro": "Jardim das Rosas",
        "cidade": "Curitiba",
        "situacao_familia": "Pais vivos, sem irmãos",
        "saude_especiais": "Nenhum",
        "observacao_geral": "Cliente bastante organizado"
    },
    {
        "nome_completo": "Luiz Pereira",
        "data_nascimento": "1995-08-10",
        "cpf": "44455566600",
        "telefone": "11911112222",
        "endereco": "Rua das Acácias",
        "rua": "Rua J",
        "numero": "777",
        "complemento": "Casa",
        "bairro": "Jardim das Orquídeas",
        "cidade": "Porto Alegre",
        "situacao_familia": "Pais falecidos, sem irmãos",
        "saude_especiais": "Nenhum",
        "observacao_geral": "Cliente bastante reservado"
    },
    {
        "nome_completo": "Patrícia Costa",
        "data_nascimento": "1991-02-28",
        "cpf": "22233344400",
        "telefone": "11988889999",
        "endereco": "Alameda dos Ipês",
        "rua": "Rua K",
        "numero": "888",
        "complemento": "Apartamento 501",
        "bairro": "Jardim das Flores",
        "cidade": "Campinas",
        "situacao_familia": "Pais vivos, um irmão",
        "saude_especiais": "Nenhum",
        "observacao_geral": "Cliente bastante amigável"
    }
]
